FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04

# Setup timezone
RUN echo 'Etc/UTC' > /etc/timezone && \
    ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime && \
    apt-get update && apt-get install -y tzdata

# Install packages to add ROS repository
RUN apt-get install -y dirmngr gnupg2
# Add ROS repository
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu bionic main" > /etc/apt/sources.list.d/ros-latest.list'
# Keys for ROS repository
RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
# Install ROS bootstrap tools
RUN apt-get update && apt-get install --no-install-recommends -y \
    python-rosdep \
    python-rosinstall \
    python-vcstools
# Set up rosdep
RUN rosdep init
RUN rosdep update
# Install ROS-Base packages
RUN apt-get update && apt-get install -y ros-melodic-ros-base

# Install packages to build caffe
RUN apt-get update && apt-get install -y \
    libprotobuf-dev \
    libleveldb-dev \
    libsnappy-dev \
    libopencv-dev \
    libhdf5-serial-dev \
    protobuf-compiler \
    libatlas-base-dev \
    python-dev \
    libgflags-dev \
    libgoogle-glog-dev \
    liblmdb-dev
RUN apt-get update && apt-get install -y --no-install-recommends libboost-all-dev

# Make catkin workspace
RUN mkdir -p /root/catkin_ws/src
RUN /bin/bash -c "source /opt/ros/melodic/setup.bash && cd /root/catkin_ws && catkin_make"

# Download pwc_net_ros
RUN cd /root/catkin_ws/src && git clone https://github.com/fujimo-t/pwc_net_ros.git
# Download Caffe for FlowNet2
RUN cd /root && git clone https://github.com/xmfbit/flownet2
# Download PWC-Net
RUN cd /root && git clone https://github.com/NVlabs/PWC-Net.git

# Patch to Caffe from PWC-Net
RUN cp /root/PWC-Net/Caffe/warping_code/warp_layer.cu /root/PWC-Net/Caffe/warping_code/warp_layer.cpp /root/flownet2/src/caffe/layers/
RUN cp /root/PWC-Net/Caffe/warping_code/warp_layer.hpp /root/flownet2/include/caffe/layers/
# Set make config to Caffe
RUN cp /root/catkin_ws/src/pwc_net_ros/docker/caffe/Makefile.config /root/flownet2/
# Build Caffe for PWC-Net
RUN cd /root/flownet2 && make all 
# Build PWC-Net ROS
RUN cd /root/catkin_ws/src && git clone https://github.com/ActiveIntelligentSystemsLab/ros_optical_flow.git
RUN /bin/bash -c "source /opt/ros/melodic/setup.bash && source /root/catkin_ws/devel/setup.bash && cd /root/catkin_ws && rosdep install -r -y pwc_net"
RUN /bin/bash -c "source /opt/ros/melodic/setup.bash && source /root/catkin_ws/devel/setup.bash && cd /root/catkin_ws && catkin_make"

# Load ROS environment at each run
COPY ./ros_entrypoint.sh /
ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]
